name: "Build and upload to PyPI"
on:
  release:
    types: ["published"]
  workflow_dispatch:

jobs:
  upload:
    uses: "matrix-org/backend-meta/.github/workflows/release.yml@v1"
    with:
      repository: pypi
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_ACCESS_TOKEN }}
